# R5S (家) WireGuard + 路由配置片段 —— 追加到 /etc/config/network

config interface 'office'
    option proto 'wireguard'
    option private_key 'CCcheSATcsQN5nl89QzhY2eLz6qHnU6kuAgyvWy12Vg='
    option multipath 'off'
    option listen_port '50000'
    list addresses '10.0.1.1/24'
    option nohostroute '1'

config wireguard_office
    option description 'office'
    option public_key 'bdE8As9hmJz+FxxnX+OtmPrvsWxq0Dy9nlxpl5Q1z2g='
    list allowed_ips '10.0.0.0/24'
    list allowed_ips '192.168.33.0/24'

config route 'tunnel_company'
    option interface 'office'
    option target '10.0.0.0'
    option netmask '255.255.255.0'

config route 'company_33_direct'
    option interface 'office'
    option target '192.168.33.0'
    option netmask '255.255.255.0'
