# 公司 x86 WireGuard + 路由配置片段 —— 追加到 /etc/config/network

config interface 'home'
    option proto 'wireguard'
    option private_key '+EB5fs9Edz/gxGu69D9ckzUY0rg0RdKNSOYEo5Qmc0s='
    option multipath 'off'
    option listen_port '50000'
    list addresses '10.0.0.1/24'
    option peers 'wireguard_home'
    option ifname 'home'

config wireguard_home 'wireguard_home'
    option public_key '+ywj9NwNnfk2HgLd0H65ie8KvUFMKZ117Z847dLoPVQ='
    option endpoint_host 'sunsanrdp.aituning.com'
    option endpoint_port '50000'
    option allowed_ips '10.0.1.0/24'
    option persistent_keepalive '25'

config route 'tunnel_home'
    option interface 'home'
    option target '10.0.1.0'
    option netmask '255.255.255.0'
